name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CMake, Make, and basic utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make build-essential wget

      - name: install duckdb
        run: |
          make install-duckdb

      - name: make all
        run: |
          make all

      - name: make test
        run: |
          make test
